chore: add non-zero exit code if no extracted binary

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -34,13 +34,19 @@ install() {
         echo "Creating ${toolname} bin directory"
         mkdir -p "${bin_install_path}"
 
-        echo "Extracting ${toolname} archive"
+        extracted=false
         if [[ $download_path == "*.tar.gz" ]]; then
+            echo "Extracting ${toolname} tar archive"
             tar xv --strip-components=2 -C "$bin_install_path" -f "${download_path}" "$(basename -s .tar.gz "$download_path")/$toolname"
+            [ $? -eq 0 ] && extracted=true
         elif [[ $download_path == "*.zip" ]]; then
+            echo "Extracting ${toolname} zip archive"
             unzip -d "$bin_install_path" "${download_path}" "$(basename -s .zip "$download_path")/$toolname"
+            [ $? -eq 0 ] && extracted=true
         fi
-
+        if [ ! $extracted ]; then
+            echo "Error: did not properly extract ${toolname} from archive"
+            exit 1
     else
         echo "Error: ${toolname} version ${version} not found" >&2
         exit 1
